config/routes.rb
Rails.application.routes.draw do
  
  root 'home#home'
  resources :shipments
  resources :tracks
  get '/track' =>  'tracks#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :shipments
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      flash[:notice] = "Login successful!"

      redirect_to '/shipments'
    else
      flash[:notice] = "Incorrect Username or Password. Please try again."

    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_filter :authorize
  def index
    wf = 'https://api.forecast.io/forecast/8b0e1f8b53a5e7e0e6b2a1b2ced3ceda/32.7150,-117.1625'
    @weather = HTTParty.get(wf).parsed_response
    @city = "Santa Monica, CA"
    @shipments = Shipment.all
  end

  def new

  end

  def create
 require 'easypost'
 EasyPost.api_key = 'sFfFy3otb2g0hjzjWaqB6A'

 to_address = EasyPost::Address.create(
   :name => params[:tname],
   :street1 => params[:tstreet1],
   :street2 => params[:tstreet2],
   :city => params[:tcity],
   :state => params[:tstate],
   :zip => params[:tzip],
   :country => params[:tcountry],
   :phone => params[:tphone],
   :email => params[:temail]
 )
 from_address = EasyPost::Address.create(
   :name => params[:fname],
   :street1 => params[:fstreet1],
   :street2 => params[:fstreet2],
   :city => params[:fcity],
   :state => params[:fstate],
   :zip => params[:fzip],
   :phone => params[:fphone],
   :email => params[:femail]
 )

 parcel = EasyPost::Parcel.create(
   :width => params[:width],
   :length => params[:length],
   :height => params[:height],
   :weight => params[:weight]
 )

 customs_item = EasyPost::CustomsItem.create(
   :description => '',
   :quantity => 2,
   :value => 23.56,
   :weight => 33,
   :origin_country => 'us',
   :hs_tariff_number => 123456
 )
 customs_info = EasyPost::CustomsInfo.create(
   :integrated_form_type => 'form_2976',
   :customs_certify => true,
   :customs_signer => 'Dr. Pepper',
   :contents_type => 'gift',
   :contents_explanation => '', # only required when contents_type => 'other'
   :eel_pfc => 'NOEEI 30.37(a)',
   :non_delivery_option => 'abandon',
   :restriction_type => 'none',
   :restriction_comments => '',
   :customs_items => [customs_item]
 )

 shipment = EasyPost::Shipment.create(
   :to_address => to_address,
   :from_address => from_address,
   :parcel => parcel,
   :customs_info => customs_info
 )

 shipment.buy(
   :rate => shipment.lowest_rate
 )

 shipment.insure(amount: 100)


 puts shipment.insurance

 redirect_to shipment.postage_label.label_url

end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :authorize

  def index
    @track_number = params[:tracking_number]
    @track_me = "https://track.aftership.com/#{@track_number}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
      if user.save
        session[:user_id] = user.id
        redirect_to '/shipments'
      else
        redirect_to '/signup'
      end
  end
end
private
   def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end

app/views/home/home.html.erb
<div class="fold-board">
<div class="container">
<div class="user-hello">
  <% if current_user %>
  <p class="user-hello-copy"><span><strong>Hello</strong>, <%= current_user.name %>, welcome back! </span>
  <span class="time-clock pull-right"><span class="glyphicon glyphicon-time"></span> <%=Time.now.strftime("%A %B %d %Y") %></span></p>
  <%end%>
</div>
<div class="ship-block col-xs-6">
<h3>Ship</h3>
<%= image_tag "mailing_label.png" %>
</div>
<div class="track-block col-xs-6">
  <h3>Track</h3>
  <%= image_tag "track-process.png" %>
</div>

</div>
</div>

app/views/layouts/_header.html.erb
<div class="top-header">
<div class="container">
<div class="col-md-4">
<h1 class="brand"><a href="/">velox<i class="glyphicon glyphicon-random"></i></a></h1>
</div>
<div class="col-md-8">
<ul class="nav navbar-nav navbar-right">
  <li><a class="sub-nav" href="/shipments">Ship</a></li>
  <li><a class="sub-nav" href="/track">Track</a></li>
  <% if current_user %>
  <li class="sub-nav"><%= link_to "Logout", '/logout' %></li>
  <% else %>

    <li class="sub-nav"><%= link_to 'Login', '/login' %></li>

    <li class="sub-nav"><%= link_to 'Signup', '/signup' %></li>
  <% end %>
</ul>
</div>
</div>
<div class="container">
  <div class="col-xs-8">
<h2 class="jumbo-title">Shipping &amp; Tracking Easy</h2>
<p class="jumbo-purpose">
  <strong>velox</strong> is an opensource app to instantly <a style="color: ghostwhite;" href="/shipments"><strong>create</strong></a> and <a style="color: ghostwhite;" href="/track"><strong>manage</strong></a><br/>
  shipping labels with our multi-carrier.</p>

</div>
<div class="col-xs-4">
<span class="pull-right"><%= image_tag "mailing_label.png" %></span>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Velox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
</head>
<body>
  <% if flash[:message] %>
      <b><%= flash[:message] %></b>
    <% end %>
  <%= render 'layouts/header' %>
<%= yield %>
</body>
</html>

app/views/shipments/_form.html.erb
<form id="myform" class="mysign-in" action="/shipments" method="post">
    <div class="col-xs-5">
  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">
  <div id="errors">
    <%= flash[:errors].join("<br>").html_safe if flash[:errors] %>
  </div>
  <div class="form-container">
    <h3 class="section-title">From</h3>

        <input type="text" name="fname" class="form-control" placeholder="Full Name" required>



        <input type="text" name="fstreet1" class="form-control" placeholder="Street Address" required>

        <input type="text" name="fstreet2" class="form-control" placeholder="APT or Floor Number" required>


        <input type="text" name="fcity" class="form-control" placeholder="City" required>



        <input type="text" name="fstate" class="form-control" placeholder="State" required>


        <input type="text" name="fzip" class="form-control" placeholder="ZIP" required>
        <input type="text" name="fphone" class="form-control" placeholder="Phone Number" required>
        <input type="text" name="femail" class="form-control" placeholder="Email" required>
      </div>
  </div>

   <div class="col-xs-4">
  <div class="form-container">
    <h3 class="section-title">To</h3>
        <input type="text" name="tname" class="form-control" placeholder="Full Name" required>

        <input type="text" name="tstreet1" class="form-control" placeholder="Street Address" required>

        <input type="text" name="tstreet2" class="form-control" placeholder="APT or Floor Number" required>

        <input type="text" name="tcity"  class="form-control" placeholder="City" required>

        <input type="text" name="tstate" class="form-control" placeholder="State" required>
        <input type="text" name="tzip" class="form-control" placeholder="ZIP" required>
        <input type="text" name="tphone" class="form-control" placeholder="Phone Number" required>
        <input type="text" name="temail" class="form-control" placeholder="Email" required>
      </div>
    </div>
    <div class="col-xs-3">
    <div class="form-container">
      <h3 class="section-title">Parcel Size</h3>

          <input type="text" name="length" class="form-control" placeholder="Length" required>

          <input type="text" name="width" class="form-control" placeholder="Width" required>

          <input type="text" name="height" class="form-control" placeholder="Height" required>

          <input type="text" name="weight" class="form-control" placeholder="Weight" required>
        </div>
  </div>

<div class="print-label btn pull-right">
  <button type="submit" class="btn btn-basic btn-lg"><span class="glyphicon glyphicon-print"></span> Print Shipping Label</button>
</div>
<p class="pull-right">You will be redirected to an external link to print your label.</p>
</div>
  </form>

app/views/shipments/_tabledata.html.erb
  <table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>To</th>
      <th>From</th>
      <th>Tracking Code</th>
      <th>Cost</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

      <tr>
        <td>2015-11-21 09:12 </td>
        <td>Vanessa Bransburg </td>
        <td>Jonathan Figueroa</td>
        <td>9499907123456123456781</td>
        <td>$3.07</td>
        <td><a href="http://assets.geteasypost.com/postage_labels/labels/20151121/f26974f8f56c4b8c8ca58b056870d7a1.png" target="_blank"><strong>View</strong></a></td>
      </tr>
      <tr>
        <td>2015-11-21 07:46 </td>
        <td>Vanessa Bransburg </td>
        <td>Jonathan Figueroa</td>
        <td>9499907123456123456781</td>
        <td>$3.44</td>
        <td><a href="http://assets.geteasypost.com/postage_labels/labels/20151121/d9dc9e17047a4dbe909292369d49f07b.png" target="_blank"><strong>View</strong></a></td>
      </tr>
      <tr>
        <td>2015-11-20 20:39  </td>
        <td>Vanessa Bransburg </td>
        <td>Jonathan Figueroa</td>
        <td>9499907123456123456781</td>
        <td>$9.97</td>
        <td><a href="http://assets.geteasypost.com/postage_labels/labels/20151120/056b3b2e008a40debb057b5f5fa436fd.png" target="_blank"><strong>View</strong></a></td>
      </tr>
  </tbody>
</table>

app/views/shipments/index.html.erb
<div class="internal-fold">
<div class="container">
  <div class="user-hello">
    <% if current_user %>
    <p class="user-hello-copy"><span><strong>Hello</strong>, <%= current_user.name %>, welcome back! </span>
    <span class="time-clock pull-right"><span class="glyphicon glyphicon-time"></span> <%=Time.now.strftime("%A %B %d %Y") %></span></p>
    <%end%>
  </div>

  <div class="col-xs-8">
  <a class="btn btn-link" href="/" role="button"><strong>&#171; Go to Main</strong></a>
  <h3>Ship or Track</h3>
  <p><span class="btn btn-default"><%= link_to 'New Shipment', new_shipment_path %></span> <strong>Or</strong> <span class="btn btn-default"><%= link_to 'Track Shipment', tracks_path %></span></p>
  <%= render 'tabledata'%>
  </div>
  <div class="col-xs-4">
  <div style="margin-right: 45px;" class="pull-right">
  <h3><span class="glyphicon glyphicon-map-marker"></span> <span><strong> <%= @city %></strong></span></h3>
  <p class="temp"><%=@weather['currently']['temperature'].floor %><sup class="sup">&deg; | F</sup>
    <span class="summary"><%=@weather['currently']['summary'] %></span></p>

  <p style="font-weight: normal;">Precipitation:<%=@weather['currently']['precipProbability'] %><sup class="">&#37;</sup> | Humidity:<%=@weather['currently']['humidity'] %><sup class="">&#37;</sup></p>

</div>
</div>
</div>
</div>

app/views/shipments/new.html.erb
<div class="internal-fold">
<div class="container">
  <div class="user-hello">
    <% if current_user %>
    <p class="user-hello-copy"><span><strong>Hello</strong>, <%= current_user.name %>, welcome back! </span>
    <span class="time-clock pull-right"><span class="glyphicon glyphicon-time"></span> <%=Time.now.strftime("%A %B %d %Y") %></span></p>
    <%end%>
  </div>
  <a class="btn btn-link" href="/" role="button"><strong>&#171; Go to Main</strong></a>
  <h3>Create Shipping Label</h3>
  <p><span class="btn btn-default btn-sm"><%= link_to 'New Shipment', new_shipment_path %></span> <strong>Or</strong> <span class="btn btn-default btn-sm"><%= link_to 'Track Shipment', tracks_path %></span></p>
  <%= render 'form'%>
</div>
</div>

app/views/tracks/_form.html.erb
<div class="container">
<form id="parcel-form" action="javascript:void(0)" accept-charset="UTF-8" method="post">

<input name="utf8" value="✓" type="hidden"><input name="authenticity_token" value="HkVBfxfw7UinPT2xLKnjPIixB+GM11PnFnP6CUvprAwDbnPJ6digR6fbSbokYcV8thfLGoMHY5oYyYWF/vLR8Q==" type="hidden">
<h6>
From Address:
</h6>
<div class="row-fluid">
<div class="col-xs-3">
<label for="Name">Name</label>
<input name="shipment[from_address][name]" id="shipment_from_address_name" placeholder="Dr. Steve Brule" class="form-control" type="text">
</div>
<div class="col-xs-3">
<label for="Company">Company</label>
<input name="shipment[from_address][company]" id="shipment_from_address_company" placeholder="Brule Inc." class="form-control" type="text">
</div>
<div class="col-xs-4">
<label for="Street_Address_1">Street address 1</label>
<input name="shipment[from_address][street1]" id="shipment_from_address_street1" placeholder="179 N Harbor Dr" class="form-control" type="text">
</div>
<div class="col-xs-2">
<label for="Street_Address_2">Street address 2</label>
<input name="shipment[from_address][street2]" id="shipment_from_address_street2" placeholder="#2" class="form-control" type="text">
</div>
</div>
<div class="row-fluid">
<div class="col-xs-3">
<label for="City">City</label>
<input name="shipment[from_address][city]" id="shipment_from_address_city" placeholder="Redondo Beach" class="form-control" type="text">
</div>
<div class="col-xs-2">
<label for="State_Province">State/province</label>
<input name="shipment[from_address][state]" id="shipment_from_address_state" placeholder="CA" class="form-control" type="text">
</div>
<div class="col-xs-2">
<label for="Postal_Code">Postal code</label>
<input name="shipment[from_address][zip]" id="shipment_from_address_zip" placeholder="90277" class="form-control" type="text">
</div>
<div class="col-xs-2">
<label for="Country">Country</label>
<input name="shipment[from_address][country]" id="shipment_from_address_country" placeholder="US" class="form-control" type="text">
</div>
<div class="col-xs-3">
<label for="Phone">Phone</label>
<input name="shipment[from_address][phone]" id="shipment_from_address_phone" placeholder="(415) ESY-POST" class="form-control" type="text">
</div>
</div>
<h6>
To Address:
</h6>
<div class="row-fluid">
<div class="col-xs-3">
<label for="Name">Name</label>
<input name="shipment[to_address][name]" id="shipment_to_address_name" placeholder="Cal Naughton Jr." class="form-control" type="text">
</div>
<div class="col-xs-3">
<label for="Company">Company</label>
<input name="shipment[to_address][company]" id="shipment_to_address_company" placeholder="Naughton Racing" class="form-control" type="text">
</div>
<div class="col-xs-4">
<label for="Street_Address_1">Street address 1</label>
<input name="shipment[to_address][street1]" id="shipment_to_address_street1" placeholder="300 Granelli Ave" class="form-control" type="text">
</div>
<div class="col-xs-2">
<label for="Street_Address_2">Street address 2</label>
<input name="shipment[to_address][street2]" id="shipment_to_address_street2" placeholder="#9" class="form-control" type="text">
</div>
</div>
<div class="row-fluid">
<div class="col-xs-3">
<label for="City">City</label>
<input name="shipment[to_address][city]" id="shipment_to_address_city" placeholder="Half Moon Bay" class="form-control" type="text">
</div>
<div class="col-xs-2">
<label for="State_Province">State/province</label>
<input name="shipment[to_address][state]" id="shipment_to_address_state" placeholder="CA" class="form-control" type="text">
</div>
<div class="col-xs-2">
<label for="Postal_Code">Postal code</label>
<input name="shipment[to_address][zip]" id="shipment_to_address_zip" placeholder="94019" class="form-control" type="text">
</div>
<div class="col-xs-2">
<label for="Country">Country</label>
<input name="shipment[to_address][country]" id="shipment_to_address_country" placeholder="US" class="form-control" type="text">
</div>
<div class="col-xs-3">
<label for="Phone">Phone</label>
<input name="shipment[to_address][phone]" id="shipment_to_address_phone" placeholder="(415) 456-7890" class="form-control" type="text">
</div>
</div>
<h6>
Parcel:
</h6>
<div class="row-fluid">
<div class="col-xs-3">Length (inches)</div>
<div class="col-xs-3">Width (inches)</div>
<div class="col-xs-3">Height (inches)</div>
<div class="col-xs-3">Weight (ounces)</div>
</div>
<div class="row-fluid">
<div class="col-xs-3">
<input name="shipment[parcel][length]" id="shipment_parcel_length" placeholder="10.0" class="form-control" type="text">
</div>
<div class="col-xs-3">
<input name="shipment[parcel][width]" id="shipment_parcel_width" placeholder="8.0" class="form-control" type="text">
</div>
<div class="col-xs-3">
<input name="shipment[parcel][height]" id="shipment_parcel_height" placeholder="9.0" class="form-control" type="text">
</div>
<div class="col-xs-3">
<input name="shipment[parcel][weight]" id="shipment_parcel_weight" placeholder="13.5" class="form-control" type="text">
</div>
</div>
<br>
<h6>
USPS Rates only.
</h6>
<input name="commit" value="Find Rates" id="submit-parcel-form" class="submit-button btn btn-blue btn-mini" type="submit">
<div id="spinner"></div>
<div class="alert" id="rate-errors" style="">
There is an error with your form.  Please fill the form out completely.
</div>
</form>
<table class="table table-bordered table-striped table">
<thead>
<tr>
<th>Service</th>
<th>Price (USD)</th>
<th>Carrier</th>
</tr>
</thead>
<tbody id="parcel-form-results"></tbody>
</table>
</div>

app/views/tracks/index.html.erb
<div class="container">
  <div class="user-hello">
    <% if current_user %>
    <p class="user-hello-copy"><span><strong>Hello</strong>, <%= current_user.name %>, welcome back! </span>
    <span class="time-clock pull-right"><span class="glyphicon glyphicon-time"></span> <%=Time.now.strftime("%A %B %d %Y") %></span></p>
    <%end%>
  </div>
  <a class="btn btn-link" href="/" role="button"><strong>&#171; Go to Main</strong></a>  
<h3>Tracks Shipments</h3>
<h4>My Tracking Number: <%=params[:tracking_number]%></h4>
<%= form_tag("/track", method: "get") do %>
<p style="width: 680px;"><%= text_field_tag(:tracking_number) %></p>
<%= submit_tag("Track", :class => "btn btn-basic" ) %>
<% end %>
<iframe style="margin-left: -40px; clip:rect(190px,1100px,800px,250px);" seamless src="https://track.aftership.com/<%=params[:tracking_number]%>" width="98%" height="800px" frameborder="0"scrolling="no" ></iframe>
</div>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<div class="fold-board">
<div class="container">
  <div class="col-xs-2"></div>
  <div class="col-xs-8">
<h3>Signup!</h3>
<div class="form-group">
<%= form_for :user, url: '/users' do |f| %>
<label for="name"> Full Name<sup>*</sup></label>
  <%= f.text_field :name, :class => "form-control" %>
  <label for="email">Email<sup>*</sup></label>
  <%= f.text_field :email, :class => "form-control" %>
  <label for="password">Password<sup>*</sup></label>
  <%= f.password_field :password, :class => "form-control" %>
  <label for="password_confirmation">Password Confirmation<sup>*</sup></label>
  <%= f.password_field :password_confirmation, :class => "form-control" %><br/>
  <%= f.submit "Submit", :class => " form-control btn btn-primary"  %>
<% end %>
</div>
<div class="col-xs-2"></div>
 </div>
</div>
</div>